# Requires snapcraft snapcraft 7.3.1.post21+gitfa823013 from edge or later to build this snap
name: snap-webkit-how
version: git
summary: 'Blah'
description: |
     Blah blah:

grade: stable
confinement: devmode
base: core22
architectures:
  - build-on: [amd64]

apps:
  gitm:
    command: bin/gitm
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - home
      - gsettings
      - network
      - network-bind
      - removable-media
    extensions:
      - gnome

parts:
  build-the-python-stuff-please:
    plugin: python
    source: .
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libsdl2-2.0-0
    python-packages:
      - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
